apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg5
  name: testhtml-loadbalancer
spec:
  loadBalancerIP: 51.140.94.151
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: testhtml
